[package]
name = "crsp"
version = "0.1.0"
edition = "2018"
description = "CHIP-8 emulator"
license = "MIT"
repository = "https://github.com/hcsch/crsp/"
keywords = ["emulator", "chip-8"]
categories = ["emulators"]

[dependencies]
crsp-base = { version = "0.1.0", path = "../crsp-base" }
